preset: symfony

enabled:
  - newline_after_open_tag
  - ordered_use
  - short_array_syntax
  - binary_operator_spaces
  - cast_spaces
  - concat_with_spaces

disabled:
  - unalign_equals
  - concat_without_spaces
